Save the date. Creates message from date/marriers.
ec-utblidningar-web20-csharp-intro/AgileProject pull request #38
Opened 2021-06-04 18:05 UTC by 3grabs7

Implemented email function for emailing all guests.
Testing for formatting of generated message

2021-06-06 11:23 UTC, Palmeuh requested changes
Bra kod men seeding saknas för email vilket skapar error i testkoden, måste fixas innan merge.

2021-06-06 11:26 UTC, 3grabs7 commented
kan vi skapa en email för appen som vi skickar cardsen ifrån? så vi kan testa att utskicken fungerar.
kanske öppna issue för att göra ett snyggare utskick i html?

2021-06-06 12:30 UTC, 3grabs7 commented
Error handling på emails nu. Så vi kan testa att carden går att skapa men hoppar över skicka iväg emails tills vi har seedade bröllop med fungerande guestUsers. Ska vi merga nu eller först sätta uåå email för appen och testa det?

2021-06-09 08:27 UTC, Palmeuh approved these changes

2021-06-09 08:27 UTC, merged